### ISSUE TITLE
Dies when scanned by nmap

### ISSUE THREAD

**Issue by kernelzeroday** [macos-fuse-t/go-smb2#1]
server output:
```
INFO[0000] debug level false
INFO[0000] Starting server at 127.0.0.1:8082
ERRO[0034] error: connection error: read tcp 127.0.0.1:8082->127.0.0.1:62926: read: connection reset by peer
ERRO[0044] error: connection error: read tcp 127.0.0.1:8082->127.0.0.1:62951: read: connection reset by peer
ERRO[0050] error: connection error: invalid transport format
ERRO[0055] error: connection error: invalid transport format
ERRO[0060] error: connection error: invalid transport format
ERRO[0065] error: connection error: invalid transport format
ERRO[0070] error: connection error: invalid transport format
ERRO[0075] error: connection error: invalid transport format
ERRO[0085] error: connection error: unexpected EOF
ERRO[0090] error: connection error: unexpected EOF
ERRO[0090] error: connection error: invalid transport format
ERRO[0098] error: connection error: invalid transport format
ERRO[0103] error: connection error: invalid transport format
ERRO[0108] error: connection error: invalid transport format
panic: runtime error: slice bounds out of range [:50831452] with capacity 113

goroutine 114 [running]:
github.com/macos-fuse-t/go-smb2/server.(*conn).runReciever(0x1400018a800)
	/Users/name/code/go-smb2/server/conn.go:266 +0x94c
created by github.com/macos-fuse-t/go-smb2/server.(*Server).Serve in goroutine 19
	/Users/name/code/go-smb2/server/server.go:203 +0x4ec
```

nmap output:

```
Starting Nmap 7.94 ( https://nmap.org ) at 2023-11-30 09:00 PST
Stats: 0:00:36 elapsed; 0 hosts completed (1 up), 1 undergoing Service Scan
Service scan Timing: About 0.00% done
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00010s latency).
Other addresses for localhost (not scanned): ::1

PORT     STATE SERVICE          VERSION
8082/tcp open  blackice-alerts?

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 68.94 seconds
```

nmap arguments:  `nmap -p 8082 localhost -A`

thanks,
kelsey

**Comment by macos-fuse-t** [comment]
fixed
